version: '3'

services:
  web:
    build: .
    volumes:
      - .:/var/www/html
      - php_vendor:/var/www/html/vendor
    ports:
      - "8080:8080"
    environment:
      CI_ENVIRONMENT: development
      DATABASE_HOST: db
    command: php spark serve --host 0.0.0.0

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: codeigniter
    tty: true

volumes:
    postgres_data:
    php_vendor:
