name: PHPUnit

on:
  push:

jobs:
  main:
    name: Build and test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: test
        run: |
          docker-compose up --build -d web
          sleep 4
          make test
